[general]
enabled = yes
port = 5038
bindaddr = 0.0.0.0
; Kapalı devre — Docker internal network, şifre basit tutuldu

[admin]
secret = admin
permit=0.0.0.0/0.0
read = system,call,log,verbose,agent,user,config,dtmf,reporting,cdr,dialplan
write = system,call,agent,user,config,command,reporting,originate
