[modules]
autoload=yes

; WebRTC için gerekli modüller
load => res_http_websocket.so
load => res_pjsip_transport_websocket.so
load => codec_opus.so

[global]
noload => res_snmp.so
noload => res_smdi.so
